
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	font-family:Arial, Helvetica, sans-serif;
	font-size:14px;
	color:#000000;
}

.main_holder {
	float:left;
	background-color:#eeeeee;
	margin: 0px auto;
	width:500px;
	border: 1px solid #beb9b7;
	padding:20px;
	margin-top:20px;
	font-family:Arial, Helvetica, sans-serif;
	font-size:14px;
}
.main_holder h1 {
	font-size:20px;
	margin:0px;
	padding:0px;
}

.main_holder table {
	empty-cells: hide;
}

.main_holder h2 {
	font-size:16px;
	margin:0 0 0 20px;
	font-weight:bold;
	margin:0px;
	padding:0px;
}
.main_holder table td{
	padding:10px;
	vertical-align:middle;
}
.main_holder table td.widthtest{
	width:400px;
}


Skill_Type{
	font-size:16px;
	font-weight:bold;
}
Agent_Skills {
	font-size:16px;
	margin:0 0 0 20px;
	font-weight:bold;
	margin:0px;
	padding:0px;
}

.bold {
	font-size:16px;
	margin:0 0 0 20px;
	font-weight:bold;
}
.blue {
	color:#006699;
}
.Green {
	color:#009900
}
.hidden {
	


.input {
	float:right;
	margin-top:10px;
}
.clear_both {
	clear:both;
	margin: 0 0 20px 0;
}